export default function About() {
    const backgroundstyle = {
        // width: "100%",
        // minHeight: "calc(100vh - 80px)",
        // height: "auto",
        // display: "flex",
        // flexDirection: "column",
        // align-items: "center",
        paddingTop: "20px",
        paddingBottom: "20px",
        color: "white",
        backgroundColor: "#121417",
    };

    const elementsStyle = {
        width: "75%",
        margin: "auto",
    };

    return (
        <div style={backgroundstyle}>
            <div style={elementsStyle}>
                <h1>EDGE</h1>
                <p>
                We introduce EDGE, a powerful method for editable dance generation that is capable of creating realistic, physically-plausible dances while remaining faithful to arbitrary input music. EDGE uses a transformer-based diffusion model paired with Jukebox, a strong music feature extractor, and confers powerful editing capabilities well-suited to dance, including joint-wise conditioning, motion in-betweening, and dance continuation. We compare EDGE to recent methods Bailando and FACT, and find that human raters strongly prefer dances generated by EDGE.
                </p>
                <img class="img-fluid" src="./assets/media/gridsample.gif" alt="Dances generated by EDGE"></img>
            </div>
        </div>
    );
}