/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Toxic(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        props.path
        // "/test_toxic2_out/test_toxic2-transformed.glb"
    );
    const { actions } = useAnimations(animations, group);

    console.log("in here");

    useEffect(() => {
        let k = "test_toxic.pkl";
        // k = "mixamo.com";
        console.log(animations);
        console.log(actions);
        // console.log(actions[k]);
        actions[k].play();

        // setTimeout(() => {
        //     const { nodes, materials, animations } = useGLTF(
        //         "/test_toxic2_out/test_toxic2-transformed.glb"
        //     );
        //     const { actions } = useAnimations(animations, group);

        //     actions[k].play();
        // }, 2000);
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="Armature002">
                        <primitive object={nodes.mixamorigHips} />
                    </group>
                    <skinnedMesh
                        name="Alpha_Surface"
                        geometry={nodes.Alpha_Surface.geometry}
                        material={materials["Alpha_Body_MAT.007"]}
                        skeleton={nodes.Alpha_Surface.skeleton}
                    />
                    <skinnedMesh
                        name="Alpha_Joints"
                        geometry={nodes.Alpha_Joints.geometry}
                        material={materials["Alpha_Joints_MAT.007"]}
                        skeleton={nodes.Alpha_Joints.skeleton}
                    >
                        <meshPhongMaterial color="#3399ff" shininess={1000} />
                    </skinnedMesh>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/test_toxic2-transformed.glb");
